version: '3.8'

services:
  app:
    build: .
    container_name: logistics_app
    ports:
      - "5000:5000" # Flask app
      - "8501:8501" # Streamlit dashboard
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: logistics_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
